kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/mathieugery/devops-k8s/myproj-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-creds
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-creds
                  key: password
            - name: MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: backend-creds
                  key: database
            - name: MONGO_HOST
              value: "mongo"
            - name: MONGO_PORT
              value: "27017"
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: backend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31870
  selector:
    app: backend